version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: srimaan_solar_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=srimaan_solar
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
